CREATE OR REPLACE VIEW INDEX_CLF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date , t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1
        WHERE INDEX = 'CL=F';
        
CREATE OR REPLACE VIEW INDEX_DAX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_DAX
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'DAX';        
        
CREATE OR REPLACE VIEW INDEX_DJI (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_DJI
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'DJI';        
        
CREATE OR REPLACE VIEW INDEX_EEM (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_EEM
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'EEM';        
        
CREATE OR REPLACE VIEW INDEX_ESF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'ES=F';        
        
CREATE OR REPLACE VIEW INDEX_EUNLDE (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'EUNL.DE';        
        
CREATE OR REPLACE VIEW INDEX_EURGBPX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'EURGBP=X';        
        
CREATE OR REPLACE VIEW INDEX_EURUSDX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'EURUSD=X';        
        
CREATE OR REPLACE VIEW INDEX_FTSE (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'FTSE';        
        
CREATE OR REPLACE VIEW INDEX_GBPUSDX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'GBPUSD=X';        
        
CREATE OR REPLACE VIEW INDEX_GCF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'GC=F';        
        
CREATE OR REPLACE VIEW INDEX_GSPC (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'GSPC';        
        
CREATE OR REPLACE VIEW INDEX_N225 (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'N225';        
        
CREATE OR REPLACE VIEW INDEX_NDX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'NDX';        
        
CREATE OR REPLACE VIEW INDEX_NGF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'NG=F';        
        
CREATE OR REPLACE VIEW INDEX_NQF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'NQ=F';        
        
CREATE OR REPLACE VIEW INDEX_SPFEDE (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'SPFE.DE';        
        
CREATE OR REPLACE VIEW INDEX_YMF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = 'YM=F';        
        
CREATE OR REPLACE VIEW INDEX_STOXX50E (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = '^STOXX50E';        
        
CREATE OR REPLACE VIEW INDEX_VIX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 
        WHERE INDEX = '^VIX';        
        

















