CREATE OR REPLACE TABLE "CLE_LND_DEV"."CLE_FUND_SWITCH"."ATU_SUM_SWITCHES_BY_MONTH" ("DATE" DATE, "NUM_SWITCHES" INTEGER);


PUT file://<file_path>/Sum_Switches_By_Month.csv @ATU_SUM_SWITCHES_BY_MONTH/ui1682184360267

COPY INTO "CLE_LND_DEV"."CLE_FUND_SWITCH"."ATU_SUM_SWITCHES_BY_MONTH" FROM @/ui1682184360267 FILE_FORMAT = '"CLE_LND_DEV"."CLE_FUND_SWITCH"."SUM_SWITCHES_BY_MONTH"' ON_ERROR = 'SKIP_FILE_0' PURGE = TRUE;

