CREATE OR REPLACE TABLE "CLE_LND_DEV"."CLE_FUND_SWITCH"."ATU_MARKET_INDEX_DATA" ("DATE" DATE, "OPEN" FLOAT, "HIGH" FLOAT, "LOW" FLOAT, "CLOSE" FLOAT, "Adj Close" FLOAT, "VOLUME" FLOAT, "INDEX" STRING, "INDEX_TYPE" STRING, "INDEX_DESCRIPTION" STRING);

PUT file://<file_path>/Market_Index_Data.csv @ATU_MARKET_INDEX_DATA/ui1682183322023

COPY INTO "CLE_LND_DEV"."CLE_FUND_SWITCH"."ATU_MARKET_INDEX_DATA" FROM @/ui1682183322023 FILE_FORMAT = '"CLE_LND_DEV"."CLE_FUND_SWITCH"."FUND_DATA"' ON_ERROR = 'SKIP_FILE_100' PURGE = TRUE;