--select t2.Date As DATE_SWITCH, t2.NUM_SWITCHES , t1.Close AS CLOSE_DAX
--    from  CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2 INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_DAX AS t1
--        ON t2.Date = t1.Date
--        order by t2.Date;
        
select sw.Date As DATE_SWITCH, sw.NUM_SWITCHES , dax.Close AS CLOSE_DAX
                                               , CLF.Close AS CLOSE_CLF
                                               , DJI.Close AS CLOSE_DJI
                                               , CLF.Close AS CLOSE_DJI
                                               , CLF.Close AS CLOSE_ESF
                                               , CLF.Close AS CLOSE_EUNLDE
                                               , CLF.Close AS CLOSE_EURGBPX
                                               , CLF.Close AS CLOSE_EURUSDX
                                               , CLF.Close AS CLOSE_GBPUSDX
                                               , CLF.Close AS CLOSE_GCF
                                               , CLF.Close AS CLOSE_GSPC
                                               , CLF.Close AS CLOSE_NDX
                                               , CLF.Close AS CLOSE_NGF
                                               , CLF.Close AS CLOSE_YMF
                                               , CLF.Close AS CLOSE_VIX
                                               , CLF.Close AS CLOSE_NQF
                                               , CLF.Close AS CLOSE_STOXX50E
                                               , CLF.Close AS CLOSE_FTSE
                                               --, CLF.Close AS CLOSE_N225
                                               --, CLF.Close AS CLOSE_SPFEDE
    from  CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS sw 
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_DAX AS dax
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_CLF AS CLF
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_DJI AS DJI
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_EEM AS EEM
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_ESF AS ESF
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_EUNLDE AS EUNLDE
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_EURGBPX AS EURGBPX
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_EURUSDX AS EURUSDX
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_GBPUSDX AS GBPUSDX
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_GCF AS GCF
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_GSPC AS GSPC
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_NDX AS NDX
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_NGF AS NGF
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_YMF AS YMF
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_VIX AS VIX
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_NQF AS NQF
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_STOXX50E AS STOXX50E
    INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_FTSE AS FTSE
    --INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_N225 AS N225
    --INNER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_SPFEDE AS SPFEDE
        ON sw.Date = dax.Date
        and sw.Date = CLF.Date
        and sw.Date = DJI.Date
        and sw.Date = EEM.Date
        and sw.Date = ESF.Date
        and sw.Date = EUNLDE.Date
        and sw.Date = EURGBPX.Date
        and sw.Date = EURUSDX.Date
        and sw.Date = GBPUSDX.Date
        and sw.Date = GCF.Date
        and sw.Date = GSPC.Date
        and sw.Date = NDX.Date
        and sw.Date = NGF.Date
        and sw.Date = YMF.Date
        and sw.Date = VIX.Date
        and sw.Date = NQF.Date
        and sw.Date = STOXX50E.Date
        and sw.Date = FTSE.Date
        --and sw.Date = N225.Date
        --and sw.Date = SPFEDE.Date
        order by sw.Date;        
        
        
        
        
        
        
        
        
        
        
        
        
select t1.Date ,t2.Date , t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION ,t2.NUM_SWITCHES
    from  CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2 LEFT OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_DAX AS t1
        ON t2.Date = t1.Date
        where t1.Date is not null
        order by t2.Date;


select t1.Date ,t2.Date , t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION ,t2.NUM_SWITCHES
    from  CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2 LEFT OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.INDEX_DAX AS t1
        ON t2.Date = t1.Date
        --where t1.Date is not null
        order by t2.Date;



select * from "CLE_LND_DEV"."CLE_FUND_SWITCH"."ATU_MARKET_INDEX_DATA" WHERE date = '2021-01-31'





select * from "CLE_LND_DEV"."CLE_FUND_SWITCH"."ATU_FUND_SWITCHES";


CREATE OR REPLACE VIEW INDEX_CLF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
        
CREATE OR REPLACE VIEW INDEX_DAX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'DAX';        
        
CREATE OR REPLACE VIEW INDEX_DJI (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'DJI';        
        
CREATE OR REPLACE VIEW INDEX_EEM (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'EEM';        
        
CREATE OR REPLACE VIEW INDEX_ESF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'ES=F';        
        
CREATE OR REPLACE VIEW INDEX_EUNLDE (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'EUNL.DE';        
        
CREATE OR REPLACE VIEW INDEX_EURGBPX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'EURGBP=X';        
        
CREATE OR REPLACE VIEW INDEX_EURUSDX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'EURUSD=X';        
        
CREATE OR REPLACE VIEW INDEX_FTSE (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'FTSE';        
        
CREATE OR REPLACE VIEW INDEX_GBPUSDX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'GBPUSD=X';        
        
CREATE OR REPLACE VIEW INDEX_GCF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'GC=F';        
        
CREATE OR REPLACE VIEW INDEX_GSPC (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'GSPC';        
        
CREATE OR REPLACE VIEW INDEX_N225 (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'N225';        
        
CREATE OR REPLACE VIEW INDEX_NDX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'NDX';        
        
CREATE OR REPLACE VIEW INDEX_NGF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'NG=F';        
        
CREATE OR REPLACE VIEW INDEX_NQF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'NQ=F';        
        
CREATE OR REPLACE VIEW INDEX_SPFEDE (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'SPFE.DE';        
        
CREATE OR REPLACE VIEW INDEX_YMF (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = 'YM=F';        
        
CREATE OR REPLACE VIEW INDEX_STOXX50E (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = '^STOXX50E';        
        
CREATE OR REPLACE VIEW INDEX_VIX (DATE, CLOSE, INDEX_TYPE, INDEX_DESCRIPTION) AS
    select t1.Date, t1.Close, t1.INDEX_TYPE, t1.INDEX_DESCRIPTION AS Close_CL_F
    from CLE_LND_DEV.CLE_FUND_SWITCH.ATU_MARKET_INDEX_DATA AS t1 FULL OUTER JOIN CLE_LND_DEV.CLE_FUND_SWITCH.ATU_SUM_SWITCHES_BY_MONTH AS t2
        ON t2.Date = t1.Date
        WHERE INDEX = '^VIX';        
        
